version: "3.1"

services:
  postgres:
    image: postgres-pgtap:latest
    container_name: pgtap
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./tests:/tests
